create table contacts (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    created_at timestamp with time zone default now()
);
