create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    created_at timestamp with time zone default now()
);

alter table public.contacts
    add column if not exists name text;

alter table public.contacts
    add column if not exists email text;

alter table public.contacts
    add column if not exists message text;

alter table public.contacts
    add column if not exists created_at timestamp with time zone default now();
